[package]
name = "alejandro/combat"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
janitor = "howmanysmall/janitor@1.18.3"
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.2.1"
react-otter = "jsdotlua/react-otter@1.2.1"
otter = "jsdotlua/otter@1.2.1"
goodsignal = "stravant/goodsignal@0.3.1"
replica = "aykut92/replica@0.1.7"

[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"